# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bd8HGilNOkmXLzuJcLiYLSkQVGlhDaK
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# --- 1. CARREGANDO A IA E OS PARÂMETROS ---
# O st.cache_resource garante que o modelo só seja carregado uma vez (deixa o app rápido)
@st.cache_resource
def carregar_arquivos():
    # Avisamos ao Python que os arquivos estão dentro da pasta 'models/'
    modelo = joblib.load('models/modelo_isolation_forest.pkl')
    scaler = joblib.load('models/scaler_os.pkl')
    limiar = joblib.load('models/limiar_otimizado.pkl')
    return modelo, scaler, limiar

modelo, scaler, limiar = carregar_arquivos()

# --- 2. INTERFACE DO USUÁRIO ---
st.title("🕵️‍♂️ Auditoria Técnica com IA")
st.write("Insira os dados da Ordem de Serviço para verificar o risco de anomalia.")

# Criando os campos para o usuário digitar
col1, col2 = st.columns(2)
with col1:
    total_pecas = st.number_input("Total de Peças Solicitadas", min_value=0, value=1)
    tempo_resolucao = st.number_input("Tempo de Resolução (Horas)", min_value=0.0, value=2.0)
with col2:
    estado_cod = st.number_input("Código do Estado", min_value=0, value=1) # O ideal aqui é um selectbox no futuro
    linha_cod = st.number_input("Código da Linha de Produto", min_value=0, value=1)

# --- 3. PROCESSAMENTO E PREVISÃO ---
if st.button("Analisar Risco"):
    # 3.1. Criar um DataFrame com o formato exato que a IA espera
    novos_dados = pd.DataFrame({
        'total_pecas': [total_pecas],
        'tempo_resolucao_horas': [tempo_resolucao],
        'estado_cod': [estado_cod],
        'linha_cod': [linha_cod]
    })

    # 3.2. Aplicar a mesma escala (Scaler) que foi usada no Colab
    dados_padronizados = scaler.transform(novos_dados)

    # 3.3. Calcular o score da OS nova
    # Multiplicamos por -1 para seguir a mesma lógica que fizemos no treino
    score_os = modelo.decision_function(dados_padronizados) * -1

    # 3.4. Veredito final comparando com o seu limiar
    st.markdown("---")
    if score_os[0] > limiar:
        st.error(f"🚨 ALERTA DE ANOMALIA! (Score: {score_os[0]:.2f} / Limite: {limiar:.2f})")
        st.write("Esta OS tem um comportamento suspeito e deve ser verificada.")
    else:
        st.success(f"✅ ATENDIMENTO NORMAL (Score: {score_os[0]:.2f} / Limite: {limiar:.2f})")
        st.write("As métricas estão dentro do padrão aceitável da empresa.")
